### Quick sanity check on Intragroup Manifold Analyzer

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.signal import find_peaks

from miscope import load_family
from miscope.analysis import saddle_transport as st

family = load_family('modulo_addition_1layer')

/home/megano/projects/mechinterp/training-dynamics-workbench/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Newly analyzed model

In [2]:
variant_a = family.get_variant(prime=101, seed=485, data_seed=42)
loader_a = variant_a.artifacts
results_a = loader_a.load_cross_epoch("intragroup_manifold")

for key in results_a.keys():
    print(f"key: {key}, shape: {results_a[key].shape}, len(shape): {len(results_a[key].shape)}")

key: group_freqs, shape: (5,), len(shape): 1
key: group_sizes, shape: (5,), len(shape): 1
key: epochs, shape: (328,), len(shape): 1
key: r2_linear, shape: (328, 5), len(shape): 2
key: r2_quadratic, shape: (328, 5), len(shape): 2
key: r2_curvature, shape: (328, 5), len(shape): 2
key: a, shape: (328, 5), len(shape): 2
key: b, shape: (328, 5), len(shape): 2
key: c, shape: (328, 5), len(shape): 2
key: shape_int, shape: (328, 5), len(shape): 2


In [3]:
print(f"shape_int: {results_a['shape_int']}")
final_r2c = results_a['r2_curvature'][-1, :]
print(f"final_r2c.shape: {final_r2c.shape}")

shape_int: [[1. 0. 2. 2. 0.]
 [2. 0. 2. 0. 0.]
 [2. 0. 2. 0. 0.]
 ...
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
final_r2c.shape: (5,)


### Untouched model

In [4]:
variant_b = family.get_variant(prime=101, seed=485, data_seed=598)
loader_b = variant_b.artifacts
results_b = loader_b.load_cross_epoch("intragroup_manifold")

for key in results_b.keys():
    print(f"key: {key}, shape: {results_b[key].shape}")

key: group_freqs, shape: (4,)
key: group_sizes, shape: (4,)
key: epochs, shape: (251,)
key: r2_linear, shape: (251, 4)
key: r2_quadratic, shape: (251, 4)
key: r2_curvature, shape: (251, 4)
key: a, shape: (251, 4)
key: b, shape: (251, 4)
key: c, shape: (251, 4)
key: shape_int, shape: (4,)


In [5]:
print(f"shape_int: {results_b['shape_int']}")

shape_int: [2 2 2 2]


In [6]:
_SHAPE_TO_INT = {"flat/blob": 0, "bowl": 1, "saddle": 2}
_INT_TO_SHAPE = {v: k for k, v in _SHAPE_TO_INT.items()}

n_epochs: int = 4
n_groups: int = 3
seed: int = 42
shape_choices = [0, 1, 2]
shape_choices = list(_SHAPE_TO_INT.values())
print(f"shape_choices: {shape_choices}")
rng = np.random.default_rng(seed)
shape_int = rng.choice(shape_choices, (n_epochs, n_groups)).astype(np.int32)

print(f"shape_int")

final_shape_int = shape_int[-1, :]
print(f"final_shape_int: {final_shape_int}")

final_shape = [_INT_TO_SHAPE.get(int(v), "flat/blob") for v in final_shape_int]
print(f"final_shape: {final_shape}")

shape_choices: [0, 1, 2]
shape_int
final_shape_int: [0 1 2]
final_shape: ['flat/blob', 'bowl', 'saddle']
